import sys
import tkinter
from tkinter import filedialog
import shutil
import pyaudio
import wave
import pyautogui
import random
import os
import platform
import fileinput
import pprint
import subprocess
import time
import setuptools
import py_compile
import signal
import urllib
import django
import scrapy
import http.cookiejar
import PyQt5 
import stat
import mimetypes
import http.client 
import socket
import nmap
import ftplib
import string
import threading 
import calendar
import datetime
import requests
import PIL
import sqlalchemy
import bs4 #beautifulsoup
import twisted
import numpy
import scipy
import matplotlib
import nltk #natural language toolkit
import nose
import sympy
import simplejson
import sh
import docopt
import psutil
import IPython
import getpass
import utils 
import sklearn
import pythonforandroid
import ebooklib
import cython
import cryptography
import gevent
import PyInstaller
import py2app
import execjs
